name: 'Install Arch Linux inside Podman, and Build AUR Packages'

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'List of AUR packages to build, separated by space.'
        required: true
        type: string
jobs:
  setup_arch:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7

      - name: 'Build packages inside Arch Linux Container'
        run: |
          echo "Building: ${{ inputs.packages }}"
          
          sudo tee -a "/etc/containers/registries.conf.d/10-unqualified-search-registries.conf" <<EOF
          unqualified-search-registries = ["docker.io"]
          EOF
          
          podman run --rm -e INPUT_PKGS="${{ inputs.packages }}" -v ${{ github.workspace }}:/workspace archlinux:latest /bin/bash -c '
            
            pacman-key --init

            pacman -Syu --needed --noconfirm base base-devel git

            useradd -mG wheel builder
            echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

            chmod -R a+rw /workspace

            sed -i -E "/^OPTIONS=\(/ s/([[:space:]]|\()debug([[:space:]]|\))/\1!debug\2/g" /etc/makepkg.conf
 
            sudo --preserve-env=INPUT_PKGS -u builder --set-home bash -c "
              cd /workspace
              packages=($INPUT_PKGS)
              echo $packages
              for i in ${packages[@]}; do
                git clone https://aur.archlinux.org/$i.git
                cd $i
                makepkg -s --noconfirm
                echo $i
              done
              "
              '
            
            







